spring:
  application:
    name: microhubs-backend

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/microhubs
    username: postgres
    password: 041410

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

jwt:
  secret: mySecretKeyForJwtTokenGenerationThatIsLongEnoughForHmacSha256Algorithm12345

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html